# Generated by Django 3.0.4 on 2020-04-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='State your reply here', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Summarize your question into no more than 200 words', max_length=200)),
                ('content', models.TextField(help_text='State your question here', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(help_text='Select categories applicable for this question', to='questions.Category')),
                ('reply', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Reply')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Summarize your question into no more than 200 words', max_length=200)),
                ('content', models.TextField(help_text='State your question here', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('op_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.ManyToManyField(help_text='Select categories applicable for this question', to='questions.Category')),
                ('reply', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Reply')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
