# Generated by Django 3.0.4 on 2020-04-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquestion',
            name='op_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
