# Generated by Django 3.0.4 on 2020-05-15 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200514_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatequestion',
            name='unique_url_id',
        ),
        migrations.RemoveField(
            model_name='publicquestion',
            name='unique_url_id',
        ),
        migrations.AlterField(
            model_name='privatequestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
