# Generated by Django 3.0.4 on 2020-05-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200514_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatequestion',
            name='url_id',
        ),
        migrations.RemoveField(
            model_name='publicquestion',
            name='url_id',
        ),
        migrations.AddField(
            model_name='privatequestion',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='publicquestion',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
