# Generated by Django 3.0.4 on 2020-05-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200514_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatequestion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='publicquestion',
            name='slug',
        ),
    ]
