# Generated by Django 3.0.4 on 2020-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200519_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatequestion',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='publicquestion',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
