# Generated by Django 3.0.4 on 2020-05-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200519_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatequestion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='publicquestion',
            name='slug',
        ),
    ]
