# Generated by Django 3.0.4 on 2020-05-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20200519_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatequestion',
            name='reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Reply'),
        ),
        migrations.AlterField(
            model_name='publicquestion',
            name='reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Reply'),
        ),
    ]
