# Generated by Django 3.0.4 on 2020-05-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20200527_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'New'), ('a', 'Answered'), ('p', 'Public')], default='n', help_text='Question status.', max_length=1),
        ),
    ]
