# Generated by Django 3.0.4 on 2020-06-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reply',
            field=models.TextField(blank=True, help_text='State your reply here', max_length=1000, null=True),
        ),
    ]
